server:
  port: 9020

spring:
  application:
    name: LEAVE-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/leavemgmnt
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka