spring:
  application:
    name: RESULT-SERVICE
  datasource: 
    url: jdbc:postgresql://localhost:5432/quizmgmnt
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9060
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
