spring:
  application:
    name: JaxWS

  datasource:
    driver-class: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/training
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
