spring:
  application:
    name: EMPLOYEE-SERVICE
  datasource: 
    url: jdbc:postgresql://localhost:5432/leavemgmnt
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
server:
  port: 9010
  
eureka: 
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
